CREATE SCHEMA TRANSACTION_REPORT;

CREATE TABLE TRANSACTIONS (
  TRANSACTION_DATE_TIME TIMESTAMP,
  VALUE_DATE DATE,
  REASON VARCHAR(100),
  DESCRIPTION VARCHAR(500),
  CURRENCY VARCHAR(5),
  CURRENCY_AMOUNT DOUBLE,
  CARD_NUMBER VARCHAR(20),
  EUR_AMOUNT DOUBLE,
  COUNTERPART VARCHAR(100),
  ATM_NAME VARCHAR(100),
  COUNTERPART_IBAN VARCHAR(30),
  PAYMENT_REASON VARCHAR(100),
  FOREIGN_CURRENCY VARCHAR(5),
  EXCHANGE_RATE DOUBLE,
  PRIMARY KEY (TRANSACTION_DATE_TIME, VALUE_DATE, DESCRIPTION)
)

CREATE TABLE COUNTERPARTIES (
  NAME VARCHAR(100),
  EXPENSE_KIND VARCHAR(100)
)

INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('PENNY MARKET', 'Spesa');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('PAM PANORAMA MI TIBALDI', 'Spesa');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('CDC 1070 SMA MILANO SAN G', 'Spesa');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('UPIM SAN GOTTARDO', 'Abbigliamento');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('FARMACIA STAZIONE PORTA G', 'Farmaci');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('FARMACIA MONCUCCO SNC', 'Farmaci');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('BEATO TE', 'Pranzi lavoro');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('SCARPAMONDO', 'Abbigliamento');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('ATLANTIC LORENTEGGIO', 'Pranzi lavoro');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('ESSELUNGA LORENTEGGIO', 'Spesa');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('CDC 4250 SMA MI TIBAL 920', 'Spesa');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('CASH ISP 1221-MILAN', 'Prelievo');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('CASH ISP 1220-MILAN', 'Prelievo');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('BANCA POP DI MILANO', 'Prelievo');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('UBI BANCA MILANO', 'Prelievo');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('Gabriella Gruppi', 'Affitto');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('MEDIAWORLD MI TROYA CC', 'Tempo libero');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('LORETO ARGENTINA M12', 'Abbonamento mezzi');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('CREPEATALY S.R.L. SEMPLIF', 'Cene/aperitivi/etc');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('ESSELUNGA LORENTEGGIO 697', 'Spesa');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('FABBRISCA VAPORE 7 - U', 'Tempo libero');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('FARMACIA TIBALDI', 'Farmaci');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('MC DONALD S', 'Pranzi lavoro');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('MC DONALD S 990', 'Pranzi lavoro');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('OVIESSE', 'Abbigliamento');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('PENNY MARKET 375', 'Spesa');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('PRINCI', 'Cene/aperitivi/etc');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('TINTORIA LAVANDERIA DI TE', 'Abbigliamento');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('VENCHI 384', 'Cene/aperitivi/etc');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('PIZZASLICE S.R.L.', 'Cene/aperitivi/etc');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('PAM PANORAMA MI TIBAL 125', 'Spesa');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('ESSELUNGA PAPINIANO 217', 'Spesa');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('CENTROMEDICO SANTAGOS 906', 'Visite mediche/esami clinici');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('FARMACIA STAZIONE P.T', 'Farmaci');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('NANO BLEU', 'Altro');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('PAM PANORAMA MI TIBAL 125', 'Spesa');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('MONDADORI MEGASTORE D 214', 'Tempo libero');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('ROMANO GIUSEPPE', 'Altro');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('PAGAM BOLLETT TABACCHERIA', 'Bollette');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('ESSELUNGA CASSALA 648', 'Spesa');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('OSPEDALE A.S.S.T. SANTI P', 'Visite mediche/esami clinici');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('COSE NOSTRE 237', 'Cene/aperitivi/etc');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('ATLANTIC LORENTEGGIO 576', 'Pranzi lavoro');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('PASTICCERIA SIENI', 'Altro');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('TIPOTA PUB', 'Cene/aperitivi/etc');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('CASH ISP 1560-MILAN', 'Prelievo');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('CHEBANCA SPA MILANO  ', 'Prelievo');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('ASAHI DI WU BULONG  020', 'Cene/aperitivi/etc');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('CENTRO MEDICO SANTAGO 682', 'Visite mediche/esami clinici');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('KING S PUB', 'Cene/aperitivi/etc');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('MANGIA SPAGHETTI', 'Pranzi lavoro');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('M.C. FOOD', 'Pranzi lavoro');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('FAI VILLA NECCHI 372', 'Tempo libero');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('GHE PENSI MI', 'Cene/aperitivi/etc');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('DECATHLON 00000342 373', 'Tempo libero');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('MAX 3R', 'Abbigliamento');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('CDC 8719 CORSO GENOVA 820', 'Spesa');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('FARMACIA IMPERIA SNC DI M', 'Farmaci');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('PANINO GIUSTO S.R.L.', 'Cene/aperitivi/etc');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('CDI CENTRO DIAGNOSTIC 610', 'Visite mediche/esami clinici');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('AEROGARA- PRISTIGASHTI', 'Viaggi');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('FIM CO 2015 OOD', 'Viaggi');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('DELABAR OOD', 'Viaggi');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('BAR 3-SOFIA AIRPORT', 'Viaggi');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('ALL AMERICAN DINER SRL', 'Cene/aperitivi/etc');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('BERTAME LORENZO', 'Pranzi lavoro');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('CENTROMEDICO SANTAGOS 045', 'Visite mediche/esami clinici');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('D  G', 'Cene/aperitivi/etc');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('FARMACIA DEI PADRI FB 988', 'Farmaci');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('JUST CAFE 294', 'Cene/aperitivi/etc');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('MEDIA WORLD', 'Tempo libero');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('RISTORANTE FRESCO CIM 412', 'Cene/aperitivi/etc');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('RISTORANTE IL CAMINO', 'Cene/aperitivi/etc');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('CONBIPEL 055', 'Abbigliamento');
INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES ('SCARPE  SCARPE 479', 'Abbigliamento');
