--Expenses grouped by kind
SELECT 
C.EXPENSE_KIND AS Spesa,
''  AS Controparte,
SUM(CURRENCY_AMOUNT) AS Importo
FROM TRANSACTIONS T
JOIN COUNTERPARTIES C ON T.COUNTERPART = C.NAME
GROUP BY Spesa

UNION

SELECT 
REASON AS Spesa,
COUNTERPART AS Controparte,
SUM(CURRENCY_AMOUNT) AS Importo
FROM TRANSACTIONS T
LEFT JOIN COUNTERPARTIES C ON T.COUNTERPART = C.NAME
WHERE C.NAME IS NULL
GROUP BY REASON, COUNTERPART

UNION

SELECT 
'Totale' AS Spesa,
'' AS Controparte,
SUM(CURRENCY_AMOUNT) AS Importo
from TRANSACTIONS;