--Expenses grouped by kind and period
SELECT 
C.EXPENSE_KIND AS Spesa,
''  AS Controparte,
DATE_FORMAT(VALUE_DATE, "%Y-%m") AS Periodo,
SUM(CURRENCY_AMOUNT) AS Importo
FROM TRANSACTIONS T
JOIN COUNTERPARTIES C ON T.COUNTERPART = C.NAME
GROUP BY Spesa, Periodo

UNION

SELECT 
REASON AS Spesa,
COUNTERPART AS Controparte,
DATE_FORMAT(VALUE_DATE, "%Y-%m") AS Periodo,
SUM(CURRENCY_AMOUNT) AS Importo
FROM TRANSACTIONS T
LEFT JOIN COUNTERPARTIES C ON T.COUNTERPART = C.NAME
WHERE C.NAME IS NULL
AND REASON NOT IN (
'GIRO DA MIEI CONTI',
'GIRO VERSO MIEI CONTI',
'CARTA CREDITO ING DIRECT',
'RICARICA PREPAGATA'
)
GROUP BY REASON, COUNTERPART, Periodo

UNION

SELECT 
'Totale' AS Spesa,
'' AS Controparte,
 '' AS Periodo,
SUM(CURRENCY_AMOUNT) AS Importo
FROM TRANSACTIONS
WHERE REASON NOT IN (
'GIRO DA MIEI CONTI',
'GIRO VERSO MIEI CONTI',
'CARTA CREDITO ING DIRECT',
'RICARICA PREPAGATA'
);

--Insert statements for new counterparties
SELECT CONCAT('INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES (''', T.COUNTERPART, ''', '''');') AS INSERT_STMT
FROM TRANSACTIONS T
LEFT JOIN COUNTERPARTIES C
ON T.COUNTERPART = C.NAME
WHERE C.EXPENSE_KIND IS NULL;