--Expenses grouped by kind
SELECT 
C.EXPENSE_KIND AS Spesa,
''  AS Controparte,
SUM(CURRENCY_AMOUNT) AS Importo
FROM TRANSACTIONS T
JOIN COUNTERPARTIES C ON T.COUNTERPART = C.NAME
GROUP BY Spesa

UNION

SELECT 
REASON AS Spesa,
COUNTERPART AS Controparte,
SUM(CURRENCY_AMOUNT) AS Importo
FROM TRANSACTIONS T
LEFT JOIN COUNTERPARTIES C ON T.COUNTERPART = C.NAME
WHERE C.NAME IS NULL
AND REASON NOT IN (
'GIRO DA MIEI CONTI',
'GIRO VERSO MIEI CONTI'
)
GROUP BY REASON, COUNTERPART

UNION

SELECT 
'Totale' AS Spesa,
'' AS Controparte,
SUM(CURRENCY_AMOUNT) AS Importo
from TRANSACTIONS;

--Insert statements for new counterparties
SELECT CONCAT('INSERT INTO COUNTERPARTIES (NAME, EXPENSE_KIND) VALUES (''', T.COUNTERPART, ''', '''');') AS INSERT_STMT
FROM TRANSACTIONS T
LEFT JOIN COUNTERPARTIES C
ON T.COUNTERPART = C.NAME
WHERE C.EXPENSE_KIND IS NULL;